### ISSUE TITLE
using 15 years rainfall data for input

### ISSUE THREAD

**Issue by maimron** [kiranaw/PeatFire#1]
Anna,
just come to my mind, I think one of important features of model is providing generalization. and currently we only works on 2015 data, but in other hand we have 15 years rainfall data.
we also have 15 years burnt-scars data from Gembil.

What do you think about using those data for input? and comparing outputs?

**Comment by kiranaw** [comment]
I think it is a good idea. We can do that.

**Comment by maimron** [comment]
each time step we can set with random (Gamma or Beta ?) number of rainfall data from the data. 
then we can compare the result with all data from the first paper eg proportion of burnt area.

**Comment by kiranaw** [comment]
@maimron I tried to modify the code, with options for both normal and gamma distributions --> https://github.com/kiranaw/PeatFire/commit/c65c43b86da8db23229c9b4dbc7b1996a2d5c1e2

**Comment by kiranaw** [comment]
just pushed the new update for 15 years rainfall data to the new branch "development" --> https://github.com/kiranaw/PeatFire/tree/development
